### ISSUE TITLE
Please update versions to flutter null safety

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [mobxjs/mobx.dart#643] opened 2021-03-16 08:51 UTC
And because build_runner >=1.12.0 depends on build_resolvers ^2.0.0, if graphql >=4.1.0-beta.1 and build_runner >=0.10.1 then build_resolvers ^2.0.0.
And because mobx_codegen >=0.4.2 depends on build_resolvers ^1.3.2 and depends on build_runner ^1.11.1, graphql >=4.1.0-beta.1 is incompatible with mobx_codegen >=0.4.2.
So, because  depends on both mobx_codegen ^1.1.2 and graphql 5.0.0-nullsafety.1, version solving failed.

**Comment by vytautas-pranskunas-** [comment] 2021-03-16 08:57
Because mobx_codegen >=0.4.2 depends on build_resolvers ^1.3.2 and build_runner >=1.12.0 depends on build_resolvers ^2.0.0, mobx_codegen >=0.4.2 is incompatible with build_runner >=1.12.0.
So, because depends on both build_runner ^1.12.1 and mobx_codegen ^1.1.2, version solving failed.

**Comment by vytautas-pranskunas-** [comment] 2021-03-16 08:57
Because build >=1.6.3 depends on analyzer ^1.0.0 and mobx_codegen >=1.1.1 depends on analyzer >=0.39.1 <0.50.0, build >=1.6.3 is incompatible with mobx_codegen >=1.1.1.
So, because depends on both mobx_codegen ^1.1.2 and build ^2.0.0, version solving failed.

**Comment by smasinde** [comment] 2021-03-18 11:21
Because mobx_codegen 1.1.2 depends on mobx ^1.1.0 and no versions of mobx_codegen match >1.1.2 <2.0.0, mobx_codegen ^1.1.2 requires mobx ^1.1.0.
So, because app depends on both mobx ^2.0.0-nullsafety.3 and mobx_codegen ^1.1.2, version solving failed.

**Comment by pavanpodila** [comment] 2021-03-21 11:53
Dupe of #598 

Null safe versions have been published for `mobx`, `flutter_mobx` and `mobx_codegen`

**Closed by pavanpodila** 2021-03-21 11:53 UTC
