### ISSUE TITLE
cause: maximum call stack size exceeded 

### ISSUE THREAD

**Issue by zhangle1** [mobxjs/mobx.dart#447] opened 2020-03-09 08:49 UTC
**Intended outcome:**
In the example form, I try to open it to display the normal meeting

**Actual outcome:**

cause: maximum call stack size exceeded

**How to reproduce the issue:**
run mobx_examples(main.dart) in Chrome
When I try to click form login,

**Versions**

flutter_mobx:1.0.1

**This is the corresponding file I generated**

part of 'form_store.dart';

// **************************************************************************
// StoreGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names, unnecessary_lambdas, prefer_expression_function_bodies, lines_longer_than_80_chars, avoid_as, avoid_annotating_with_dynamic

mixin _$FormStore on _FormStore, Store {
Computed _$isUserCheckPendingComputed;

@override
bool get isUserCheckPending => (_$isUserCheckPendingComputed ??=
Computed(() => super.isUserCheckPending))
.value;
Computed _$canLoginComputed;

@override
bool get canLogin =>
(_$canLoginComputed ??= Computed(() => super.canLogin)).value;

final _$colorAtom = Atom(name: '_FormStore.color');

@override
CustomColor get color {
$colorAtom.context.enforceReadPolicy($colorAtom);
_$colorAtom.reportObserved();
return super.color;
}

@override
set color(CustomColor value) {
_$colorAtom.context.conditionallyRunInAction(() {
super.color = value;
_$colorAtom.reportChanged();
}, $colorAtom, name: '${$colorAtom.name}_set');
}

final _$nameAtom = Atom(name: '_FormStore.name');

@override
String get name {
$nameAtom.context.enforceReadPolicy($nameAtom);
_$nameAtom.reportObserved();
return super.name;
}

@override
set name(String value) {
_$nameAtom.context.conditionallyRunInAction(() {
super.name = value;
_$nameAtom.reportChanged();
}, $nameAtom, name: '${$nameAtom.name}_set');
}

final _$emailAtom = Atom(name: '_FormStore.email');

@override
String get email {
$emailAtom.context.enforceReadPolicy($emailAtom);
_$emailAtom.reportObserved();
return super.email;
}

@override
set email(String value) {
_$emailAtom.context.conditionallyRunInAction(() {
super.email = value;
_$emailAtom.reportChanged();
}, $emailAtom, name: '${$emailAtom.name}_set');
}

final _$passwordAtom = Atom(name: '_FormStore.password');

@override
String get password {
$passwordAtom.context.enforceReadPolicy($passwordAtom);
_$passwordAtom.reportObserved();
return super.password;
}

@override
set password(String value) {
_$passwordAtom.context.conditionallyRunInAction(() {
super.password = value;
_$passwordAtom.reportChanged();
}, $passwordAtom, name: '${$passwordAtom.name}_set');
}

final _$_usernameCheckAtom = Atom(name: '_FormStore._usernameCheck');

@override
ObservableFuture get _usernameCheck {
_$usernameCheckAtom.context.enforceReadPolicy($_usernameCheckAtom);
_$_usernameCheckAtom.reportObserved();
return super._usernameCheck;
}

@override
set _usernameCheck(ObservableFuture value) {
_$_usernameCheckAtom.context.conditionallyRunInAction(() {
super._usernameCheck = value;
_$_usernameCheckAtom.reportChanged();
}, _$usernameCheckAtom, name: '${$_usernameCheckAtom.name}_set');
}

final _$validateUsernameAsyncAction = AsyncAction('validateUsername');

@override
Future validateUsername(String value) {
return _$validateUsernameAsyncAction
.run(() => super.validateUsername(value));
}

final _$_FormStoreActionController = ActionController(name: '_FormStore');

@override
void validatePassword(String value) {
final _$actionInfo = _$_FormStoreActionController.startAction();
try {
return super.validatePassword(value);
} finally {
_$FormStoreActionController.endAction($actionInfo);
}
}

@override
void validateEmail(String value) {
final _$actionInfo = _$_FormStoreActionController.startAction();
try {
return super.validateEmail(value);
} finally {
_$FormStoreActionController.endAction($actionInfo);
}
}

@override
String toString() {
final string =
'color: ${color.toString()},name: ${name.toString()},email: ${email.toString()},password: ${password.toString()},isUserCheckPending: ${isUserCheckPending.toString()},canLogin: ${canLogin.toString()}';
return '{$string}';
}
}

mixin _$FormErrorState on _FormErrorState, Store {
Computed _$hasErrorsComputed;

@override
bool get hasErrors =>
(_$hasErrorsComputed ??= Computed(() => super.hasErrors)).value;

final _$usernameAtom = Atom(name: '_FormErrorState.username');

@override
String get username {
$usernameAtom.context.enforceReadPolicy($usernameAtom);
_$usernameAtom.reportObserved();
return super.username;
}

@override
set username(String value) {
_$usernameAtom.context.conditionallyRunInAction(() {
super.username = value;
_$usernameAtom.reportChanged();
}, $usernameAtom, name: '${$usernameAtom.name}_set');
}

final _$emailAtom = Atom(name: '_FormErrorState.email');

@override
String get email {
$emailAtom.context.enforceReadPolicy($emailAtom);
_$emailAtom.reportObserved();
return super.email;
}

@override
set email(String value) {
_$emailAtom.context.conditionallyRunInAction(() {
super.email = value;
_$emailAtom.reportChanged();
}, $emailAtom, name: '${$emailAtom.name}_set');
}

final _$passwordAtom = Atom(name: '_FormErrorState.password');

@override
String get password {
$passwordAtom.context.enforceReadPolicy($passwordAtom);
_$passwordAtom.reportObserved();
return super.password;
}

@override
set password(String value) {
_$passwordAtom.context.conditionallyRunInAction(() {
super.password = value;
_$passwordAtom.reportChanged();
}, $passwordAtom, name: '${$passwordAtom.name}_set');
}

@override
String toString() {
final string =
'username: ${username.toString()},email: ${email.toString()},password: ${password.toString()},hasErrors: ${hasErrors.toString()}';
return '{$string}';
}
}

**Comment by pavanpodila** [comment] 2020-03-10 15:51
I think the problem is reference to `super` is not pointing to the base class but to the same instance. This is a quirk of JavaScript where the `this` pointer is not correctly pointing to a real **`super`**. I think this is a side-effect of not generating the correct code when doing Dart -> JS compilation.

```dart
 @override
  set _usernameCheck(ObservableFuture<bool> value) {
    _$_usernameCheckAtom.context.conditionallyRunInAction(() {
      super._usernameCheck = value;
      _$_usernameCheckAtom.reportChanged();
    }, _$_usernameCheckAtom, name: '${_$_usernameCheckAtom.name}_set');
  }

```

The line:

```dart
      super._usernameCheck = value;
```

causes the problem since `super._usernameCheck` is calling itself. We need to dig in more into the JS code to see if this can be fixed. This is most likely a bug in Dart-> JS Compiler ? @shyndman ?

**Comment by pavanpodila** [comment] 2020-03-11 04:19
Ok, after a little more digging, the problem lies with the use of private fields. This is a duplicate of the issue posted earlier (#438). By changing the `_usernameCheck` field to public (`usernameCheck`), the problem disappears. For now that is a bandaid solution, before the Dart2JS compiler generates better code for private fields.

Also closing this issue as this is being tracked in in #438.

**Closed by pavanpodila** 2020-03-11 04:19 UTC
