### ISSUE TITLE
Store mixin prevents defining dispose on base class

### ISSUE THREAD

**Issue by eltonomicon** [mobxjs/mobx.dart#217] opened 2019-07-10 05:09 UTC
The code snippet below demonstrates the issue. The problem is that since the code generator requires the Store mixin, the base class dispose gets shadowed by Store.dispose in the derived class. The only reason I use the Store mixin with the derived class is because the code generator requires it.

```
// Equivalent of Store from mobx
mixin Store {
  void dispose() {
    print('Store.dispose');
  }
}

class BaseStore = _BaseStore with _$BaseStore;

class _BaseStore with Store {
  void dispose() {
    print('BaseStore.dispose');
  }
}

//  Equivalent to mobx-generated code
mixin _$BaseStore on _BaseStore, Store {
}

class DerivedStore = _DerivedStore with _$DerivedStore;

class _DerivedStore extends BaseStore with Store {
}

// Equivalent to mobx-generated code
mixin _$DerivedStore on _DerivedStore, Store {
}

void main() {
  DerivedStore store = DerivedStore();
  // Prints 'Store.dispose', not 'BaseStore.dispose' as desired
  store.dispose();
}
```

**Comment by rrousselGit** [comment] 2019-07-10 07:50
@pavanpodila is Subclassing stores supposed to be supported?

**Comment by pavanpodila** [comment] 2019-07-10 09:58
I think it should be supported, but haven't tried yet. Currently it operates as a mixin so not sure what the end inheritance hierarchy would be if it gets subclassed. Since mixins are inserted in between the subclass and base, a super call would first hit the mixin instead of the base.

```
Base
↑
Store (mixin)
↑
Derived
```

Is my understanding correct?

**Comment by rrousselGit** [comment] 2019-07-10 10:19
The issue is that the generator requires `Derived` to mixin `Store` again even although `Base` already contains it

Which is why Base.dispose is never reached

**Comment by pavanpodila** [comment] 2019-07-10 10:35
Ah. We need to check in our codegen if the abstract class (`_DerivedStore`) is extending a class (`BaseStore`) that already mixes in a `Store`. This will have to be a change in the `mobx_codegen`.

**Comment by eltonomicon** [comment] 2019-07-10 14:50
That could work, another thought I had is the code generator could require a @store annotation rather than a Store mixin.

If subclassing stores isn't preferred, another approach could be an option for the code generator to support generating a mixin instead of a class, then functionality could be shared across stores via a mixin rather than a base class.

**Comment by pavanpodila** [comment] 2019-07-10 16:17
The `@Store` annotation could definitely simplify the boilerplate. We did consider it in one of our design discussions but I forget why we didn't do it. Perhaps now with the mixin-based Store, it would be possible to try it out again. @rrousselGit ?

**Comment by rrousselGit** [comment] 2019-07-10 16:34
We could replace `with Store` with `@Store`.

We used a base class in case we ever needed to generate methods on `Store` (like for an `any` reaction we talked earlier).

But besides the `dispose`, that mixin is currently unused (and I have yet to publish my package using `Store.dispose`).
So if we want to change that, it's definitely possible.



Similarly, why do we need these `@action`/`@observable` already?
I'm pretty sure these could be inferred from the member type (action = function, observable = property

**Comment by eltonomicon** [comment] 2019-07-10 16:58
@rrousselGit IMO it shouldn't be inferred since not all functions alter state and not all properties mutate. I suppose it wouldn't hurt anything in those cases, but I'd prefer to not have the extra generated code and runtime cost if it's not needed.

**Comment by eltonomicon** [comment] 2019-07-10 17:01
@rrousselGit One thought, maybe `@store` could have an optional parameter that indicates whether to infer or not? Then the easy case is easy, the more granular control case is still possible?

**Comment by pavanpodila** [comment] 2019-07-10 17:19
Also the @observable and @action annotations are semantic and convey the intent more clearly. Also there could be non-action and non-observable members in the class, so the annotations help in separating them.

**Comment by rrousselGit** [comment] 2019-07-10 17:32
I'll open a new issue for that discussion, it's a bit off-topic

**Comment by eltonomicon** [comment] 2019-07-11 03:49
`@store` on a store class feels better to me, it's consistent with `@observable` and `@action` and it's more explicit. It's awkward that a `Store` mixin is required for code generation, a mixin feels like something that's optional, especially when it only has one empty method.

**Comment by pavanpodila** [comment] 2019-07-11 04:22
The real deal is with the generation of the `_$<YourStore>` mixin which is mixed in to create the concrete class. So ya, the `Store` is more of marker mixin right now.

**Comment by pavanpodila** [comment] 2019-07-12 06:53
Closing this in favor of the proposed feature: #225

**Closed by pavanpodila** 2019-07-12 06:53 UTC
