### ISSUE TITLE
Feature request: Allow static class variables to be @observable

### ISSUE THREAD

**Issue by matthewlloyd** [mobxjs/mobx.dart#155] opened 2019-04-23 21:21 UTC
I had a use case where I needed to mark a static field in a class as @observable, but mobx-codegen told me that's not currently possible. It would be great to have this facility. I worked around the issue by turning off code generation and just using the Observable<T> type.

**Comment by rrousselGit** [comment] 2019-04-23 21:25
The problem is, the code generator works by overriding getters/setters for decorated fields.

But that is not possible to do with static fields.

**Comment by pavanpodila** [comment] 2019-04-24 01:04
One option is to move those fields to a separate Store class and then keep a static reference to the class.

**Comment by pavanpodila** [comment] 2019-04-28 12:43
closing this for now

**Comment by matthewlloyd** [comment] 2019-04-28 19:58
Worth noting that it does seem to be possible to override getters and setters for static fields, so maybe this has changed recently in Dart. The code below does seem to work, so this may be possible (it might even be trivial). I haven't tried with mixins or abstract classes, though.

```
class A {
  static var foo = 1;
}

class B extends A {
  @override
  static get foo => A.foo * 10;

  @override
  static set foo(val) => A.foo = val;
}

void main() {
  print(A.foo);
  print(B.foo);
  B.foo = 2;
  print(A.foo);
  print(B.foo);
}
```

Output (from DartPad, SDK 2.2):

```1
10
2
20
```

**Comment by pavanpodila** [comment] 2019-04-29 04:37
Thanks for sharing that @matthewlloyd. This is definitely interesting and worth looking into further.

**Comment by matthewlloyd** [comment] 2019-05-05 17:46
I attempted to implement this but ran into the following problem. Although it is possible to override getters and setters for static fields, it isn't possible when the overrides come from mixins.

```
class StaticField = _StaticField with _$StaticField;

abstract class _StaticField {
  static String staticField = 'initialValue';
}

// generated code
mixin _$StaticField on _StaticField {
  @override
  static String get staticField {
    return _StaticField.staticField;
  }

  @override
  static set staticField(String value) {
    _StaticField.staticField = value;
  }
}

void main() {
  print(StaticField.staticField);
}
```

```
Error compiling to JavaScript:
main.dart:37:21:
Error: Getter not found: 'staticField'.
  print(StaticField.staticField);
                    ^^^^^^^^^^^
Error: Compilation failed.
```

**Closed** 2019-05-05 17:47 UTC

**Comment by pavanpodila** [comment] 2019-05-06 02:22
Aha, thanks for the investigation @matthewlloyd !!
