### ISSUE TITLE
mobx_codegen generates invalid code when observable is of type Color

### ISSUE THREAD

**Issue by sergeyv** [mobxjs/mobx.dart#165] opened 2019-05-06 04:26 UTC
I'm trying to define a model which has attributes of type Color (dart.ui.Color):

```
import 'package:mobx/mobx.dart';
part "Label.g.dart";

class Label = LabelBase with _$Label;
abstract class LabelBase  implements Store {
  @observable 
  Color bgColor;
}
```

The generated code in Label.g.dart, however, uses `dynamic`:

  final _$bgColorAtom = Atom(name: 'LabelBase.bgColor');

```
  @override
  dynamic get bgColor {
    _$bgColorAtom.reportObserved();
    return super.bgColor;
  }

  @override
  set bgColor(dynamic value) {
    _$bgColorAtom.context.checkIfStateModificationsAreAllowed(_$bgColorAtom);
    super.bgColor = value;
    _$bgColorAtom.reportChanged();
  }
```

which results in a compile-time error:

> Error: The return type of the method '_$Label.bgColor' is 'dynamic', which does not match the return type, 'Color', of the overridden method, 'LabelBase.bgColor'.
>  - 'Color' is from 'dart:ui'.                                           
> Change to a subtype of 'Color'.                                         
>   dynamic get bgColor {            

Am I doing something wrong or is it a problem with mobx_codegen?

**Comment by pavanpodila** [comment] 2019-05-06 06:51
I don't see an import for `dart:ui`. Is that present somewhere in the code ?

**Comment by pavanpodila** [comment] 2019-05-06 07:23
This seems to be related to this issue with build_runner: https://github.com/dart-lang/json_serializable/issues/236

**Comment by pavanpodila** [comment] 2019-05-06 11:22
After digging a bit deep, it looks like an issue with **`source_gen`**, where it is not able to discover the type correctly and thus marks it as dynamic.  Will have to follow up with their team on this with a repro.

**Comment by rrousselGit** [comment] 2019-05-06 11:31
This is a known issue. All code-generators suffer from the same limitation.

I make a temporary workaround on `functional_widget` by manually parsing the tokens.

**Comment by rrousselGit** [comment] 2019-05-06 11:33
The problem is, code-generators do not use Dart from the Flutter SDK. They use Dart from the server SDK.

The one with `dart:mirror` but no `dart:ui`. So any times from `dart:ui` are not resolved.

**Comment by pavanpodila** [comment] 2019-05-06 11:33
@rrousselGit Any suggestions how we should handle in `mobx_codegen`. We are relying on the source_gen to give us the right type.

**Comment by rrousselGit** [comment] 2019-05-06 11:35
I don't think there's a clean way to do it. The only solution is to wait and see. Libraries can't do anything.

You can try parsing tokens, but Mobx relies on decorators so that'll be a lot more complex to do. And even then it's not perfect

**Comment by pavanpodila** [comment] 2019-05-06 11:36
> The problem is, code-generators do not use Dart from the Flutter SDK. They use Dart from the server SDK.
> 
> The one with `dart:mirror` but no `dart:ui`. So any type from `dart:ui` won't resolve.

Oh boy! I don't see a clear path forward here 😢

**Comment by pavanpodila** [comment] 2019-05-06 11:38
How about we wrap the **`dart:ui`** types with a custom type, which is from the same package? Not ideal but a workaround nonetheless.

**Comment by rrousselGit** [comment] 2019-05-06 11:45
That seems to work. It's probably a good workaround

**Comment by rrousselGit** [comment] 2019-05-06 11:50
related: https://github.com/dart-lang/build/issues/733

**Comment by pavanpodila** [comment] 2019-05-06 11:55
I just did a quick test with the following:

```dart
// Needs a constructor
class CustomColor extends Color {
  CustomColor(int value) : super(value);
}
```

It generates the output correctly now:

```dart
  final _$colorAtom = Atom(name: '_FormStore.color');

  @override
  CustomColor get color {
    _$colorAtom.reportObserved();
    return super.color;
  }

  @override
  set color(CustomColor value) {
    _$colorAtom.context.checkIfStateModificationsAreAllowed(_$colorAtom);
    super.color = value;
    _$colorAtom.reportChanged();
  }

```

I think with this workaround, we can close it.

**Comment by pavanpodila** [comment] 2019-05-06 11:57
Thanks a lot @rrousselGit for pointing in the right direction and clarifying why this was failing!

**Closed** 2019-05-06 15:24 UTC
Labels: not related, wontfix

**Comment by shyndman** [comment] 2019-08-25 04:55
Hey there.

Just a head's up that MobX will now output dart:ui types. No more dynamic!

**Comment by pavanpodila** [comment] 2019-08-25 05:05
All published now:

- **mobx** `0.3.7`
- **mobx_codegen** `0.3.6`

**Comment by gustavolramos** [comment] 2023-12-03 14:04
I had this issue yesterday, here's my relevant code for the observable:

```
part 'controller.g.dart';

class Controller = ControllerBase with _$Controller;

abstract class ControllerBase with Store {
@observable
  ObservableList<Color> blockColors = ObservableList<Color>();
}
```
Also here's the equivalent code for the "controller.g.part" file:

```
  @override
  ObservableList<InvalidType> get blockColors {
    _$blockColorsAtom.reportRead();
    return super.blockColors;
  }

  @override
  set blockColors(ObservableList<InvalidType> value) {
    _$blockColorsAtom.reportWrite(value, super.blockColors, () {
      super.blockColors = value;
    });
  }
```
This is the error that shows on the generated file:

The name 'InvalidType' isn't a type, so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'InvalidType'.

This is my current Flutter Doctor:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [versÆo 10.0.19045.3693], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2022.2)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Community Edition (version 2022.2)
[√] VS Code (version 1.84.2)
[√] Connected device (3 available)
[√] Network resources

Also here's my pubspec.yaml

```
name: sisterly_game_challenge
description: "Flutter Developer position challenge"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_mobx: ^2.2.0
  mobx: ^2.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.7
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
```

Any idea why this still happens?
